### ISSUE TITLE
request for metrics code

### ISSUE THREAD

**Issue by OneWorld-github** [matthias-k/DeepGaze#1]
I would very much appreciate it if metrics code was included in this repo, so that the same visualisations that you see from this website

https://deepgaze.bethgelab.org/submissions/ef2eba2b-e171-455a-aa09-b4096d802484

are reproducible from a run.py file in this repo.

Otherwise, it appears that users of this repo would only have a tensor output, that needs post processing to get it to look like the results in the link above.

**Comment by matthias-k** [comment]
Hi! The code for the visualizations is part of [pysaliency](https://github.com/matthias-k/pysaliency). Are you referring to the visualization of the model prediction? Then have a look at `pysaliency.plotting.visualize_distribution`. The saliency maps for the different metrics are also accessible via pysaliency, check out http://openaccess.thecvf.com/content_ECCV_2018/html/Matthias_Kummerer_Saliency_Benchmarking_Made_ECCV_2018_paper.html and  https://github.com/matthias-k/saliency-benchmarking/blob/master/saliency_benchmarking/saliency_map_provider.py#L12 for details. Let me know if you have any further questions.
