### ISSUE TITLE
License

### ISSUE THREAD

**Issue by behinger** [matthias-k/DeepGaze#13]
Hi Matthias,
I was wondering under what license DeepGaze is published (currently none?).

In my specific case a small request, could you release this image: https://github.com/matthias-k/DeepGaze/blob/main/figures/deepgaze3_prediction.png under CC-By? I want to use it in public teaching materials :-)

Keep up the amazing work!!
Cheers, Benedikt

**Comment by matthias-k** [comment]
Hi Benedikt!

Hereby I release https://github.com/matthias-k/DeepGaze/blob/main/figures/deepgaze3_prediction.png under CC-BY. Let me know if you need more :). I'm glad you want to use my work for your teaching!

Best,
  Matthias
