### ISSUE TITLE
HTTP Error 300: Multiple Choices when using pretrained DeepGazeIIE，while it works on DeepGazeI

### ISSUE THREAD

**Issue by LuZeking** [matthias-k/DeepGaze#2]
Hi, thanks for your awesome code, but when I use the DeepGazeIIE model, "urllib.error.HTTPError: HTTP Error 300: Multiple Choices" raised in the line model = deepgaze_pytorch.DeepGazeIIE(pretrained=True).to(DEVICE), while it works on DeepGazeI instead of DeepGazeIIE.

**Comment by LuZeking** [comment]
solved! the torch should download from 'pytorch/vision:v0.10.0' now

**Comment by ManooshSamiei** [comment]
For me the issue persists. I am using google colab
