### ISSUE TITLE
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 242, 256]

### ISSUE THREAD

**Issue by ManooshSamiei** [matthias-k/DeepGaze#3]
I get this error when calling model on image and center bias tensors:
`
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 242, 256]`

**Comment by ManooshSamiei** [comment]
Also there is a parenthesis extra at the end of the code you have shared in readme.

**Comment by matthias-k** [comment]
The torch model expects batches of images, i.e. of shape `batch_size x height x width x 3` for the images and `batch_size x height x width` for the center bias. If you're processing only one image, make sure to put them into a batch of size 1 (as in the README). If that's not the problem, could you please provide me with a snippet of how you're using the model?

**Comment by matthias-k** [comment]
> is a parenthesis extra at the end of the code you have shared in readme.

Thanks! I just fixed the typo.

**Comment by Sharvari-t** [comment]
Hello, 
I'm facing this error too when running this off from the readme file without any modifications. RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 440, 512]. Please let me know the possible solution.

**Comment by matthias-k** [comment]
I tried around a bit, but I don't manage to reproduce this error when running the code from the readme. I tested torch v1.8.1 and 1.10.2. Can you please let me know which torch version you're using? Are you using the latest version of the README?

**Comment by tatue64** [comment]
I also observed the above-mentioned runtime error, but only after the upgrade to torch 1.11. This suggests that there is a regression in version 1.11.

**Comment by gregorbaer** [comment]
I had the same errors. Specifically installing pytorch=1.10.2 and the corresponding torchvision version fixed this problem for me.

**Comment by matthias-k** [comment]
Thanks for the debug help! It seems `conv1d` got a bit more strict about its input since 1.11. I'll try to adapt my code to make it compatible with new torch versions.

**Comment by schrtim** [comment]
Hi, I am trying to get the demo running as well. I am running torch 1.11.0+cu113 on my system.
I am getting the same error as @tugcegurbuz is there any update on this matter yet, or do you have any suggestions what we could investigate to resolve this error, s.t. one can use your code on a new GPU?

**Comment by matthias-k** [comment]
I just pushed a bugfix ([a2f6037](https://github.com/matthias-k/DeepGaze/commit/a2f6037f9ae20086ff19775583ed036167449172)) that should make the code run again with torch 1.11. Let me know if there are still any problems.
