### ISSUE TITLE
Issues with loading densenet

### ISSUE THREAD

**Issue by JacobSchildknecht** [matthias-k/DeepGaze#4]
I am getting an HTTP 300 Error as i am trying to build a DeepGaze IIE model. The error happens during the load of the densenet 201 model in densenet.py (`self.densenet = torch.hub.load('pytorch/vision:v0.5.0', 'densenet201', pretrained=True) `).

**Comment by matthias-k** [comment]
@JacobSchildknecht thanks for the report! The source was a change in the behaviour of github and torch (see https://github.com/pytorch/pytorch/issues/74368). I just pushed a fix, it should work now again.

**Comment by JacobSchildknecht** [comment]
Thanks for the quick reply and solve, but i get the next issue (same HTTP Error) during the download of ResNext50 model (`self.resnext = torch.hub.load('pytorch/vision:v0.5.0', 'resnext50_32x4d', pretrained=True)`), as it is also using pytorch vision 0.5.0.

**Comment by matthias-k** [comment]
Ah, I see. Then I need to check all models. Usually the fix is simply to update to `vision:v0.6.0`, but I need to check for each case whether the new version is still using exactly the same parameters.

**Comment by JacobSchildknecht** [comment]
Thank you for the quick reply and for the fix
